# Generated by Django 2.1.7 on 2019-02-24 17:49

import apps.upload.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='csv-files/sample-data.csv', upload_to='csv-files/', validators=[apps.upload.validator.validate_file_extension]),
        ),
    ]
