# Generated by Django 2.1.7 on 2019-03-30 19:36

import apps.upload.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190224_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='csv-files/500-data.csv', upload_to='csv-files/', validators=[apps.upload.validator.validate_file_extension]),
        ),
    ]
