# Generated by Django 2.1.7 on 2019-03-30 21:54

import apps.upload.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190330_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='csv-files/', validators=[apps.upload.validator.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
